### ISSUE TITLE
DEVMODE structure has fields with incorrect types

### ISSUE THREAD

**Issue by Skrity** [microsoft/win32metadata#1325]
### Which crate is this about?

windows

### Crate version

0.42.0

### Summary

When querying display via EnumDisplaySettings(A,W,ExA,ExW) display parameters get inserted into wrong fields. Tested on 2 pcs so far.

### Toolchain version/configuration

Default host: x86_64-pc-windows-gnu
rustup home:  C:\_scoop\persist\rustup\.rustup

stable-x86_64-pc-windows-gnu (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)

### Reproducible example

```rust
fn main() {
    use windows::Win32::Graphics::Gdi::*;
    let mut dm = DEVMODEA::default();
    dm.dmSize = std::mem::size_of_val(&dm) as u16;
    let b = unsafe {EnumDisplaySettingsExA(windows::core::PCSTR::null(), ENUM_CURRENT_SETTINGS, &mut dm, 0u32) };
    println!("Result: {:?}",b);
    println!("dmBitsPerPel: {:?}", dm.dmBitsPerPel);
    println!("dmPelsWidth: {:?}", dm.dmPelsWidth);
    println!("dmPelsHeight: {:?}", dm.dmPelsHeight);
    println!("dmDisplayFrequency: {:?}", dm.dmDisplayFrequency);
    println!("others");
    println!("dmSpecVersion: {:?}", dm.dmSpecVersion);
    println!("dmDriverVersion: {:?}", dm.dmDriverVersion);
    println!("dmDriverExtra: {:?}", dm.dmDriverExtra);
    println!("dmLogPixels: {:?}", dm.dmLogPixels);
    println!("dmICMMethod: {:?}", dm.dmICMMethod);
}
```

### Crate manifest

```toml
[package]
name = "test_refresh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.windows]
version = "0.42.0"
features = ["Win32_Foundation", "Win32_Graphics_Gdi"]
```

### Expected behavior

Result: BOOL(1)
dmBitsPerPel: *
dmPelsWidth: 2560
dmPelsHeight: 1440
dmDisplayFrequency: 165
others
dmSpecVersion: *
dmDriverVersion: *
dmDriverExtra: *
dmLogPixels: *
dmICMMethod: *

### Actual behavior

Result: BOOL(1)
dmBitsPerPel: 1440
dmPelsWidth: 0
dmPelsHeight: 165
dmDisplayFrequency: 0
others
dmSpecVersion: 1025
dmDriverVersion: 1025
dmDriverExtra: 0
dmLogPixels: 2560
dmICMMethod: 0
