### ISSUE TITLE
MEVT constants are missing from windows::Win32::Media::Audio

### ISSUE THREAD

**Issue by cogwheel** [microsoft/win32metadata#1714]
### Summary

According to [the documentation for MIDIEVENT](https://learn.microsoft.com/en-us/windows/win32/api/mmeapi/ns-mmeapi-midievent), there should be constants for the different event types such as:

- `MEVT_SHORTMSG`
- `MEVT_TEMPO`
- `MEVT_NOP`

etc.

However these do not appear [anywhere in `windows-rs`](https://microsoft.github.io/windows-docs-rs/doc/windows/?search=MEVT_)

### Crate manifest

```TOML
[package]
name = "poc-windows-midi-streambuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scopeguard = "1.2.0"

[dependencies.windows]
version = "0.51.0"
features = ["Win32_Foundation", "Win32_Media_Audio"]
```

### Crate code

```Rust
N/A; just install the dependencies and look in the crate.
```
